Directory.Build.props
src/Sdk/Models/AddAliasRequest.cs

Preventing NRTs is particularly crucial in library code

Enable strict NRTs

---

.editorconfig
.github/workflows/release.yml
.github/workflows/workflow.yml
Directory.Build.props
src/Passwordless/Passwordless.csproj

- Added some extra package metadata
- Enabled sourcelink (lets users of the library navigate directly to GitHub sources of various symbols)
- Enabled inline documentation (we already have inline docs, we were just not publishing them)
- Enabled embedded debug symbols (works better than publishing symbols separately)
- Enabled reproducible builds (ensures same source always produces the same binary, scrubs non-deterministic info)

Add package metadata, sourcelink, inline docs, debug symbols, enable reproducible builds

---

src/Passwordless.AspNetCore/IdentityBuilderExtensions.cs

This will set ApiKey on the PasswordlessOptions object that's injected into the IServiceCollection.

Added ApiKey to the Options config

---

README.md
src/Passwordless.AspNetCore/README.md

It doesn't work on NuGet.org readme preview

Remove little icons from readme headers

---

.github/workflows/bump.yml
.github/workflows/main.yml
Directory.Build.props

This adds a new, dispatchable workflow called `bump`. You can use it to update the current package version (of both `Passwordless` and `Passwordless.AspNetCore`). It does that by updating `Directory.Build.props`, committing changes to a new branch, and then creating a pull request. Very similar to what @abergs did in #27.
In order to facilitate this workflow, I also took the liberty of performing one additional breaking change: auto-generated prerelease package versions for CI deployments now follow the pattern of `0.0.0-ci-BRANCH-RUNID`. The main difference is that the version is always `0.0.0`.
This change was done so that we could consolidate both `VersionPrefix` and `VersionSuffix` into a single `Version` property. It's not essential for this workflow to work, but then instead of one …

Add bump workflow

---

.github/workflows/main.yml

This sends a message in Slack on successful stable release deployment, with the following content:
```
Passwordless.NET new version released!
Version: 1.0.2
Details: https://github.com/passwordless/passwordless-dotnet/releases/tag/v1.0.2
```

Notify Slack on successful release deploy

---

examples/Passwordless.Example/Passwordless.Example.csproj
examples/Passwordless.Example/PasswordlessController.cs
src/Passwordless.AspNetCore/IdentityBuilderExtensions.cs
src/Passwordless/ServiceCollectionExtensions.cs

Fix service registration for `PasswordlessClient`

---

tests/Passwordless.AspNetCore.Tests/Passwordless.AspNetCore.Tests.csproj
tests/Passwordless.AspNetCore.Tests/RegistrationTests.cs

This should fail in CI but might be helpful in fixing #56 that `git bisect` points me to #45. This can be merged after a fix is merged or cherry picked into the PR that does the fixing.
@Tyrrrz

Add RegistrationTests

---

examples/Passwordless.AspNetIdentity.Example/.gitignore
examples/Passwordless.AspNetIdentity.Example/appsettings.json
src/Passwordless/Helpers/Extensions/HttpExtensions.cs
src/Passwordless/Passwordless.csproj
src/Passwordless/PasswordlessHttpHandler.cs
src/Passwordless/PasswordlessHttpRequestExtensions.cs

Fix HTTP request message being marked as completed too early

---

src/Passwordless/PasswordlessClient.cs

https://bitwarden.atlassian.net/browse/PAS-219

Send SDK version in headers

---

src/Passwordless/IPasswordlessClient.cs
src/Passwordless/Models/VerifiedUser.cs
tests/Passwordless.Tests/TokenTests.cs

Some more tests, some of which are currently failing due to bugs on the API side

Add more tests

---

tests/Passwordless.Tests/Fixtures/TestApiFixture.cs
tests/Passwordless.Tests/Passwordless.Tests.csproj

As @justindbaur suggested.
This makes tests about 30-40seconds (35-40%) faster on CI.

Use SQLite instead of MSSQL in tests

---

.github/workflows/main.yml

This should make the move to `bitwarden` org smooth

Make GH NuGet deployments repo-agnostic

---

src/Passwordless.AspNetCore/Services/Implementations/PasswordlessService.cs
tests/Passwordless.AspNetCore.Tests.Dummy/Program.cs
tests/Passwordless.AspNetCore.Tests/EndpointTests.cs
tests/Passwordless.AspNetCore.Tests/OldTests/PasswordlessServiceTests.cs

https://bitwarden.atlassian.net/browse/PAS-260
Is this the direction we want to take?

Route Passwordless API errors in `PasswordlessService`

---

src/Passwordless/Helpers/PasswordlessSerializerContext.cs
src/Passwordless/IPasswordlessClient.cs
src/Passwordless/Models/GetEventLogRequest.cs
src/Passwordless/Models/GetEventLogResponse.cs
src/Passwordless/PasswordlessClient.cs
tests/Passwordless.Tests.Infra/TestApi.cs
tests/Passwordless.Tests/ApplicationEventLogsTests.cs

This adds GetEventLogAsync to the IPasswordlessClient. Includes an integration test to validate object deserialization.

Add GetEventLogAsync

---

.github/workflows/main.yml

These have to be updated in tandem because `4.x` versions of both actions are incompatible with `3.x` versions of each other.

Update `upload-artifact` and `download-artifact`

---

examples/Passwordless.AspNetIdentity.Example/Pages/Account/Magic.cshtml.cs
examples/Passwordless.AspNetIdentity.Example/Pages/Account/Recovery.cshtml.cs

Currently, `Magic.cshtml` only works with the DIY magic links built on the MGAT feature.  This will change the sample DIY magic link to work like the new magic link feature.
Testing done:
- i've validated the existing flow continues to work.
- the format matches the new magic link format.

Allow Magic.cshtml to Use Magic LInks

---

src/Passwordless/Models/Credential.cs

`init` properties cannot be deserialized with the JsonSerializer source generation. This moves the properties from those `init` fields to optional parameters.

Cannot deserialize init properties

---

src/Passwordless/Helpers/Extensions/DoubleExtensions.cs
src/Passwordless/Helpers/Extensions/FunctionalExtensions.cs
src/Passwordless/Helpers/PasswordlessSerializerContext.cs
src/Passwordless/IPasswordlessClient.cs
src/Passwordless/Models/AuthenticationOptions.cs
src/Passwordless/PasswordlessClient.cs

[PAS-370](https://bitwarden.atlassian.net/browse/PAS-370?atlOrigin=eyJpIjoiOGZlM2Q0ODVkMDMzNDg2MGE4YTE4MmI2NWIxODIzOGIiLCJwIjoiaiJ9)
This adds TTL to the GenerateAuthenticationTokenAsync AuthenticationOptions record.  It also adds an internal record that is used for the PasswordlessSerializerContext. This is because the API endpoint takes the TTL as an int of seconds. `TimeSpan` is a nicer way to define a segment of time, so I added the layer for ease of use.
Existing tests passed.
[PAS-370]: https://bitwarden.atlassian.net/browse/PAS-370?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Adding TTL to AuthenticationOptions

---

src/Passwordless/Passwordless.csproj
src/Passwordless/ServiceCollectionExtensions.cs

We currently cannot read updated values when the `appsettings.json` or `environment variables` change. The ASP.NET Identity SDK has to be fixed separately.

.NET SDK: Options pattern is not reading updated values

---

src/Passwordless.AspNetCore/IdentityBuilderExtensions.cs
src/Passwordless/ServiceCollectionExtensions.cs

We currently cannot read updated values when the appsettings.json or environment variables change.
This pull request fixes this issue for the ASP.NET Identity SDK. This will allow us to change api keys and api secrets without having to restart any running instances.
Adds two new overloads as well accepting a `string path` as a parameter.
('tests fail due to an unrelated issue where libsodium is likely missing in our alpine-based image.')

.ASP.NET Identity SDK: Options pattern is not reading updated values

---

.github/workflows/main.yml

Related to https://github.com/bitwarden/passwordless-devops/pull/14
Requires secret: `DEPLOYMENT_GITHUB_TOKEN`

Use dispatched deployments

---

src/Passwordless.AspNetCore/IdentityBuilderExtensions.cs

Fixes the ASP.NET Identity integration tests where the endpoints were not mapped.
- Needs further refactoring down the line.
n/a
I did the following to ensure that my changes were tested thoroughly:
I did the following to ensure that my changes did not introduce new security vulnerabilities:

Fix ASP.NET Identity endpoints integration tests

---

.github/workflows/main.yml

Looks like when the matrix has all cases excluded, the job still runs but with no parameters set. Didn't think that it would be the case -- this PR fixes that.

Run `deploy` only on release

---

tests/Passwordless.Tests.Infra/TestApi.cs

Tests are failing due to a recent change: root page (`/`) no longer has a handler and migrations are performed automatically.
This updates the health checks to fix it.
There is also another issue, with the file path for the mail sink. In development mode it's `../mail.md` which resolves to `/opt/mail.md`. The app doesn't have access to that file.
This also fixes that.

Update test container healthchecks

---

src/Passwordless.AspNetCore/IdentityBuilderExtensions.cs
src/Passwordless.AspNetCore/Passwordless.AspNetCore.csproj
src/Passwordless.AspNetCore/PasswordlessApiEndpointRouteBuilderExtensions.cs
src/Passwordless/Passwordless.csproj
src/Passwordless/ServiceCollectionExtensions.cs

Add AOT and trim analyzers

---

examples/Passwordless.AspNetIdentity.Example/Pages/Account/Register.cshtml

Closes [PAS-513](https://bitwarden.atlassian.net/browse/PAS-513)
Description:
This fixes the script tag to be module which will allow the module import.
Shape:
Added type=module to script tag
[PAS-513]: https://bitwarden.atlassian.net/browse/PAS-513?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fixing AspNetIdentity.Example Register Script

---

examples/Passwordless.AspNetIdentity.Example/Program.cs
src/Passwordless/IPasswordlessClient.cs
src/Passwordless/PasswordlessClient.cs
src/Passwordless/PasswordlessOptions.cs
src/Passwordless/ServiceCollectionExtensions.cs
tests/Passwordless.Tests.Infra/PasswordlessApplication.cs
tests/Passwordless.Tests/MagicLinksTests.cs
tests/Passwordless.Tests/ServiceRegistrationTests.cs

This PR does the following:
1. Moves the validation of `ApiSecret` from service registration (eager) to when the API requests are actually sent (lazy).
- This makes it possible to register a Passwordless client with invalid `ApiSecret` and have it fail only when the client is actually used.
- It prevents an issue in a DI scenario where a service may depend on Passwordless client, but not rely on it when the secret is not provided (think the initialization flow in the Admin Console). Previously, the validation would prevent the service from being created entirely. Now it will only fail when any of the methods on the client are called.
2. Moves the coercion of the `ApiUrl` (defaulting to `CloudApiUrl` when not set) from service registration to client initialization.
- This makes it so that …

PAS-542 | Delay and consolidate coercion and validation of `PasswordlessOptions`

---

src/Passwordless.AspNetCore/IdentityBuilderExtensions.cs
src/Passwordless/ServiceCollectionExtensions.cs
tests/Passwordless.Tests/Passwordless.Tests.csproj
tests/Passwordless.Tests/ServiceRegistrationTests.cs

This PR fixes an issue where, when registering the Passwordless Identity integration, the core options (`PasswordlessOptions`) were not initialized with reload-tracking, due to the fact that the SDK was registered with `services.AddPasswordlessSdk(_ => {})`. Even though we forwarded the options by re-registering them inside the Identity integration, this did not forward the corresponding reload token.
I also added a few tests for configuration-related scenarios, although properly e2e testing configuration routing is quite challenging.

Add `Passwordless.AspNetCore` registration overloads that support `IConfiguration` properly

---

src/Passwordless/Models/Credential.cs

We would need a new release after merging this.

PAS-563 | RPID is not mapped correctly when retrieving credentials

---

tests/Passwordless.Tests.Infra/TestApi.cs

We need compatibility for the mail providers defined in: https://github.com/bitwarden/passwordless-server/commit/8697acd192ea5a42687fb542aaff9908050ceee3
Since https://github.com/bitwarden/passwordless-server/commit/2d9dd79d36d2ff27f460875ce9cee2a9719de32c, we are setting the path directly in the image itself.
This configuration we're removing in this pull request is redundant, and will regardless no longer work as it's no longer compatible with the new format.

PAS-572 | Remove default path for mail file provider

---

.github/workflows/main.yml

https://bitwarden.atlassian.net/browse/VULN-127
Codecov updated the codecov/codecov-action GitHub action. In this new version, it no longer requires a CODECOV_TOKEN in the workflows. This PR will update the action to t
he current latest version (5.1.2) and remove the CODECOV_TOKEN for the action.
Note: The codecov/test-results-action GitHub action still requires a token, and can not be removed yet.

Updated Codecov action and removed token
